# Exceptions
validation.user.subscribe.self.error=User cannot subscribe to himself
user.not_found=User with id: %d not found